### ISSUE TITLE
Cleaner separation between computation and display?

### ISSUE THREAD

**Issue by hadley** [fmichonneau/foghorn#15]
Foghorn would be a bit easier to use programmatically if you factored the functions a little differently. Currently you have `check_cran_results()` and `summary_cran_results()` to retrieve summary tables for one or more packages, and `show_cran_results()` to show the detailed results for a single package. I think the API would be a little more elegant if you had `cran_results()` and `cran_details()` functions. `check_cran_results()` would become `cran_results()`, and `summary_cran_results` would become a summary method; `show_cran_results()` would become a print method for the object returned by `cran_details()`. This would also make foghorn easier to program with since you've separate the two tasks of parsing the results from the webpage and displaying attractive results to the user.

**Comment by fmichonneau** [comment]
That sounds like a good idea. I think I was stuck trying to mimic the ways CRAN is representing the results of the different checks. I'll look more into this and implement a more consistent API.

**Comment by fmichonneau** [comment]
Hi @hadley 

I have started to refactor the code and clean up the API following your suggestions.

As it stands, both `cran_results()` and `cran_details()` return tibbles:

```r
> cran_results(email="hadley@rstudio.com")
# A tibble: 32 x 7
         Package ERROR  FAIL  WARN  NOTE    OK has_other_issues
           <chr> <int> <int> <int> <int> <int>            <lgl>
 1    assertthat     0     0     0     0    12            FALSE
 2     babynames     0     0     0     8     4            FALSE
 3     bigrquery     0     0     0     1    11            FALSE
 4        dbplyr     0     0     0     5     7            FALSE
 5      devtools     1     0     0     0    11            FALSE
 6         dplyr     0     0     0     8     4            FALSE
 7       feather     1     0     0     6     5            FALSE
 8       forcats     0     0     0     0    12            FALSE
 9       ggplot2     1     0     0     4     7            FALSE
10 ggplot2movies     0     0     0     0    12            FALSE
# ... with 22 more rows
> cran_details(c("dplyr", "purrr"))
# A tibble: 4 x 5
  Package result                         check
    <chr>  <chr>                         <chr>
1   dplyr   NOTE        installed package size
2   dplyr   NOTE data for non-ASCII characters
3   dplyr   NOTE          package dependencies
4   dplyr   NOTE           Rd cross-references
# ... with 2 more variables: flavors <chr>, message <chr>
```

I also have a summary methods for  `cran_results()` and `cran_details()`.

```r
> summary(cran_results(pkg=c("purrr", "dplyr")))
★  Package with notes on CRAN: 
  - dplyr (8)
◉  Packages with other issues on CRAN: 
  - dplyr
  - purrr

> summary(cran_details(c("dplyr", "purrr")))
✔ All clear for  purrr !
◉ dplyr has other issues 
◉ purrr has other issues 
★ dplyr - NOTE: installed package size
   ❯ r-devel-linux-x86_64-fedora-clang 
   ❯ r-devel-linux-x86_64-fedora-gcc 
   ❯ r-devel-windows-ix86+x86_64 
   ❯ r-release-windows-ix86+x86_64 
   ❯ r-release-osx-x86_64 
   ❯ r-oldrel-windows-ix86+x86_64 
   ❯ r-oldrel-osx-x86_64 

      installed size is 27.9Mb
      sub-directories of 1Mb or more:
        libs  26.0Mb
```

Are you considering integrating `foghorn` into `devtools` (that would be sweet!)? If so, what is your time line?

I would like to improve how the "other issues" are reported and stored in the tibbles, as CRAN is now more consistent compared to when I first put this package together.

The code also relies on several packages (from the tidyverse) that are currently not dependencies of `devtools`, and I could refactor parts of the code to remove some of them if it's a concern.

Let me know if there is anything else that this package could do that would make its integration with `devtools` easier.

**Comment by hadley** [comment]
Ideally I'd like to use it as part of `release()` so instead of:

```
Have you fixed all existing problems at 
https://cran.rstudio.com/web/checks/check_results_tidyverse.html ?
```

You'd see the actual problems. 

I think it'll be at least two weeks before we do a devtools release. I think the main problem would be the dplyr and tidyr dependences as they're fairly heavy and we're trying to keep devtools lightweight (this constraint will be removed in the not too distant future as we'll a have a separate set of lighter-weight packages for use in CI environments)

**Comment by fmichonneau** [comment]
I removed the `tidyr` and `dplyr` dependencies. I kept `tibble` because `foghorn` has other dependencies that also rely on `Rcpp` (e.g. `xml2`). There are a couple of small details I'd like to fix before releasing this new version on CRAN (creating deprecated aliases for the renamed functions). In the meantime, let me know if there something else you'd need from me. (I can look into creating a PR to integrate `foghorn` into `devtools` but it's going to be a few weeks before I have time to do so).

**Comment by fmichonneau** [comment]
Thanks for your suggestion @hadley! It really made foghorn better.

foghorn is now an optional dependency of devtools, and if the user has it, during the release process, the user will be shown the CRAN check results if there are problems with the package.
