### ISSUE TITLE
FR: Show state of CRAN submission

### ISSUE THREAD

**Issue by krlmlr** [fmichonneau/foghorn#24]
Can we extract relevant information from [ftp://cran.r-project.org/incoming/](ftp://cran.r-project.org/incoming/) ?

**Comment by fmichonneau** [comment]
yes, that should be doable. Are there rules written somewhere about what the location of the package means? Or should it just report "package found in 'recheck'"?

**Comment by krlmlr** [comment]
I don't know. For starters, it might be enough to report a tidy data frame that includes the name of the directory. Maybe cross-referenced with maintainer names taken from elsewhere?

**Comment by fmichonneau** [comment]
@krlmlr I implemented this. Let me know if you have any feedback. The new function `cran_incoming()` either returns all the packages in the CRAN queue, or you can specify a vector of package names to only return the packages that might be in the queue: `cran_incoming(pkg="tibble")

**Comment by krlmlr** [comment]
Awesome, works as expected:

``` r
foghorn::cran_incoming("tibble")
#> # A tibble: 1 x 3
#>   package version cran_folder
#>   <chr>   <chr>   <chr>      
#> 1 tibble  1.4.2   recheck
```

> Created on 2018-01-22 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
