### ISSUE TITLE
R version requirement for foghorn

### ISSUE THREAD

**Issue by jimhester** [fmichonneau/foghorn#26]
For r-lib / tidyverse packages we try to support R versions from `>= 3.1`. Foghorn only supporting (>= 3.3) is therefore causing the devtools travis checks for these versions to fail. I can work around the issue, but ideally foghorn would be available for all versions we support.

Are there specific features in foghorn that preclude you from pushing back the version requirement to 3.1?

**Comment by fmichonneau** [comment]
Thanks for the suggestion. I updated by travis file to mimic the same situation as for devtools, and after one small fix (561c0027e8b2c688d60b160e862a68d02eff730a), it seems that foghorn is now compatible with R >= 3.1. I'll send off to CRAN soon.

**Comment by jimhester** [comment]
Great thanks!
