### ISSUE TITLE
Expand foghorn checks to include the new additional tests run by CRAN

### ISSUE THREAD

**Issue by coatless** [fmichonneau/foghorn#33]
`foghorn` checks are not including the new `memtests` routines that Ripley added to CRAN. Thus, the "All clear for `<PKG>`!" is a bit misleading. 

These check results can be obtained via:

```r
issues = tools::CRAN_check_issues()
```

c.f. r-lib/devtools#1976

**Comment by coatless** [comment]
@fmichonneau for the day it will be **cIRT**:

https://cran.r-project.org/web/checks/check_results_cIRT.html

c.f. "Additional issues" under the check matrix

There seems to be a matrix for checks but it doesn't contain pass/fail/note status:

https://cran.r-project.org/web/checks/check_issue_kinds.html

**Comment by fmichonneau** [comment]
OK, got it. I found the oversight. I'll get a fix in soon.
