### ISSUE TITLE
Rename vignette to foghorn.Rmd?

### ISSUE THREAD

**Issue by maelle** [fmichonneau/foghorn#36]
I've just noticed you have only one vignette, and to find it in the pkgdown website I need to click on Articles > Quick start.

If it were named foghorn.Rmd it'd automatically appear as "Get started" in the navbar, so one click less, cf e.g. [`rhub` website](https://r-hub.github.io/rhub/). (I was told that by an user, I didn't know that before either :-) )

**Comment by fmichonneau** [comment]
Thanks for the suggestion!
