### ISSUE TITLE
cran_incoming(folders="waiting") is not supported (despite being documented in master)

### ISSUE THREAD

**Issue by HenrikBengtsson** [fmichonneau/foghorn#38]
```
> foghorn::cran_incoming(folders="waiting")
Error in match.arg(folders, several.ok = TRUE) : 
  'arg' should be one of "newbies", "inspect", "pretest", "recheck", "pending", "publish", "archive"
```

It's mentioned in the help since https://github.com/fmichonneau/foghorn/commit/34d653ca83e51fe041a4eb4a24c81f1172ca445c

PS. I'd like to suggest that the version is bumped in the master branch (to e.g. 1.1.0-9000) to make it different from CRAN (1.1.0);

https://github.com/fmichonneau/foghorn/blob/71fd2620eca5e46ba18e7d16382cfbeede5067c0/DESCRIPTION#L3

**Comment by fmichonneau** [comment]
Thanks for the report @HenrikBengtsson! 

I fixed the bug, bumped the version number, and submitted a new release to CRAN (the last one was from February so it seemed like a good time to do so).
