### ISSUE TITLE
Scrape winbuilder queue

### ISSUE THREAD

**Issue by krlmlr** [fmichonneau/foghorn#40]
from e.g. ftp://win-builder.r-project.org/R-devel/, see https://blog.r-hub.io/2020/04/01/win-builder/.

**Comment by krlmlr** [comment]
Time zones seems to be off, though: Indicated as "GMT +2" in the listing, should be UTC.

**Comment by fmichonneau** [comment]
Thanks so much for the suggestion @krlmlr!
I implemented it in the commit/PR linked here. Testing/feedback is appreciated.
