### ISSUE TITLE
does winbuilder_queue() work?

### ISSUE THREAD

**Issue by bbolker** [fmichonneau/foghorn#43]
`winbuilder_queue()` seems to be returning an empty tibble, even while I've got a package that I know is in process there.  Does that mean (1) something is broken/has changed about the setup or (2) only packages that are *waiting*, not packages being processed, are listed?

I think there must be at least part of `#1` above going on, because directly visiting the URL (ftp://win-builder.r-project.org/R-devel/) shows three packages in the queue (including mine) even while `winbuilder_queue()` is returning the empty tibble. 

PS I think some of `#2` must apply as well, as the URL above (and the corresponding R-release one) are now empty, but I haven't received an updated status e-mail yet. (Assuming that the package testing is in progress - another possibility is that there's a surprisingly large lag between the end of the package testing process and my receipt of the status e-mail?)

**Comment by fmichonneau** [comment]
Thanks for the report Ben!

Yes, it looked like there was a change to the FTP server that led the function to always return an empty tibble.

You are correct that this only lists the packages as they are waiting to be processed. Do you have a suggestion on how to improve the wording in the documentation to reflect this?

**Comment by bbolker** [comment]
docs seem fine now.  I was probably just flailing around.  Thanks.
