### ISSUE TITLE
cran_incoming fails if the queue contains a package with an invalid version specification

### ISSUE THREAD

**Issue by bastistician** [fmichonneau/foghorn#45]
The incoming/archive folder currently contains an invalid package `oceans2.0_api_R_client.tar.gz`. This file doesn't adhere to the required name_version scheme and `cran_incoming()` fails with:

```
Error: invalid version specification 'api'
```

To reproduce this error also later (if the problematic file no longer exists in the archive):

```
foghorn:::parse_pkg("oceans2.0_api_R_client.tar.gz")
```

**Comment by fmichonneau** [comment]
Thanks for the report!

**Comment by bastistician** [comment]
Thanks! This was quick.

The following comment in the docs should be updated:

https://github.com/fmichonneau/foghorn/blob/84b446b5ad7cbb47f79e8ef6dbba168741ac2158/R/cran_queue.R#L162-L163
