### ISSUE TITLE
CRP now refer to http(s) instead of ftp

### ISSUE THREAD

**Issue by krlmlr** [fmichonneau/foghorn#46]
for checking "incoming".

https://github.com/eddelbuettel/crp/compare/master@%7B2020-10-29%7D...master@%7B2021-04-25%7D

**Comment by fmichonneau** [comment]
I think I took care of this in the 1.4.0 release. I updated the docs to remove mentions of the FTP queue (f36f537). Please let me know if I'm missing it somewhere. Thanks!
