### ISSUE TITLE
CRAN version of foghorn::cran_incoming() broken (invalid version specification 'api')

### ISSUE THREAD

**Issue by bbolker** [fmichonneau/foghorn#47]
With a fresh install from CRAN, `foghorn::cran_incoming()` gives

> Error: invalid version specification ‘api’

With a fresh `remotes::install_github(fmichonneau/foghorn)`, it works fine.

Time to push a new version to CRAN ... ?

**Comment by fmichonneau** [comment]
fixed with release of foghorn 1.4.2 last week. Thanks for the nudge Ben!
