### ISSUE TITLE
cran_incoming() tweaks

### ISSUE THREAD

**Issue by krlmlr** [fmichonneau/foghorn#49]
- Add a `show_archived = FALSE` argument: typically, there are too many archived packages, when is this information useful?
- Sort by date by default

``` r
foghorn::cran_incoming() |> dplyr::count(cran_folder)
#> # A tibble: 7 × 2
#>   cran_folder     n
#>   <chr>       <int>
#> 1 archive       201
#> 2 inspect        13
#> 3 newbies        15
#> 4 pending         8
#> 5 pretest         7
#> 6 publish         2
#> 7 waiting        19
```

<sup>Created on 2022-10-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Happy to contribute.

**Comment by fmichonneau** [comment]
Thank you for these ideas!
