### ISSUE TITLE
Suggestions/requests

### ISSUE THREAD

**Issue by zkamvar** [fmichonneau/foghorn#5]
Hey! I saw [your tweet][0] and I have some feedback. First, thank you for putting this together! It's nice not having to go to different cran check pages just to check the status every time a new version is released :)

## Bugs?

It works well so far, but I ran into some weirdness. It works for my main package, poppr, but it seems to be missing out on ezec:

```r
foghorn::summary_cran_checks(email = "kamvarz@science.oregonstate.edu")
## ✖ Package(s) with errors on CRAN: poppr, popprxl

foghorn::summary_cran_checks(package = c("poppr", "popprxl", "ezec", "adegenet", "mmod"))
##✖ Package(s) with errors on CRAN: adegenet, poppr, popprxl
## Warning message:
## closing unused connection 3 (https://cran.r-project.org/web/checks/check_results_zkamvar_at_gmail.com.html)
```

## Suggestion

Additionally, it would be nice to have the number of errors in the summary instead of just errors e.g:

```r
## ✖ Package(s) with errors on CRAN: poppr (2/13), popprxl (2/13)
```

This way, it's easier to see whether or not the errors are new.

[0]: https://twitter.com/fmic_/status/793577021150490625

**Comment by fmichonneau** [comment]
Hi @zkamvar 

Thanks for the feedback!

The warning you saw is from a weirdness in the way the connections are handled by the xml2 package apparently. It occurs when you try to reach an invalid URL, but the warning is only displayed in subsequent calls. You can see the email address included in the warning was your gmail's not your OSU's. I added an additional call to `close()` in the package to avoid it.

I like your suggestion about the number of errors/warnings, and I'm going to implement it!

Thanks again
