### ISSUE TITLE
Should `foghorn` error or warn if the scraper fails?

### ISSUE THREAD

**Issue by eddelbuettel** [fmichonneau/foghorn#53]
`foghorn` had been very reliable for me in automating analysis of reverse dependencies.  For 'recently' (weeks or months ago) it stopped and no longer retrieved results.  Without having looked at the code, I may be missing a package you use for scraping so maybe you skip the step silently?

Compare my existing (default) call with no extras:

```r
> cran_results(pkg=c("leidenAlg", "statgenGWAS"))
# A tibble: 0 × 7
# ℹ 7 variables: package <chr>, error <int>, fail <int>, warn <int>, note <int>, ok <int>, has_other_issues <lgl>
> 
```

which used to work.  "Lucky for me" there is an alternative:

````r
> cran_results(pkg=c("leidenAlg", "statgenGWAS"), src="crandb")
# A tibble: 2 × 7
  package     error  fail  warn  note    ok has_other_issues
  <chr>       <int> <int> <int> <int> <int> <lgl>           
1 leidenAlg       7     0     0     4     0 FALSE           
2 statgenGWAS     0     0     0    13     0 FALSE           
> 
```

If I misunderstood or missed something let me know.  The above seems to align with the basic package documentation, used to work, and should maybe warn in the former.   Thanks for putting this helpful package together.

**Comment by eddelbuettel** [comment]
Ah, I see now that in my use I had already added `src="crandb"` but, entirely by fault of mine, placed that in the wrong after a closing paren so it "applied" (without affect) to the outer function wrapped around `cran_results`.   When I correct that all is well again.

But if you could add some magic to detect when the scraper (which worked) now fails that would be awesome too.

**Comment by fmichonneau** [comment]
Thanks for the report @eddelbuettel! I'm sorry it took so long to get back to you. I had misunderstood your report. I'm preparing a new release and included your suggestion.

**Comment by eddelbuettel** [comment]
There is now a new nag (as you are likely aware) coming from your use of `httr2` and an apparently deprecated interface.
