### ISSUE TITLE
"human" folder?

### ISSUE THREAD

**Issue by krlmlr** [fmichonneau/foghorn#55]
According to the workflow in https://r-hub.github.io/cransays/articles/dashboard.html#cran-review-workflow, this is a legitimate folder that also contains several packages right now. Should foghorn be looking at that folder too?

**Comment by fmichonneau** [comment]
I am open to it. If I remember correctly, I had ignored them initially because they contained artifacts that were not packages. I'd be happy to review a PR if you had time to implement this change. Thank you for bringing this up!

**Comment by fmichonneau** [comment]
It looks like the `human` folder is gone, and the CRAN maintainers have their folders directly at the root of `incoming` now. 

![Screenshot from 2023-12-24 08-32-08](https://github.com/fmichonneau/foghorn/assets/5502922/905b09e4-692a-4257-b069-4770895a502d)

**Comment by krlmlr** [comment]
Thanks for checking!
