### ISSUE TITLE
Imports should specify crayon (>= 1.5.2)

### ISSUE THREAD

**Issue by HughParsonage** [fmichonneau/foghorn#58]
On crayon 1.5.1 it fails with error message (with e.g. `foghorn::summary_cran_results`

Error in gsub_(st$close, st$open, text, fixed = TRUE, useBytes = TRUE) : 
  could not find function "gsub_"

Updating fixed the issue.

**Comment by fmichonneau** [comment]
Thanks for the report! `crayon` is superseded by `cli` so I used this opportunity to use that package instead.
